version: "3.9"
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
